### ISSUE TITLE
docker new install, config files not created, container doesn't start.

### ISSUE THREAD

**Issue by DER31K** [hrfee/jellyfin-accounts#10]
I believe the docker container is not creating default config files, which causes container to fail to start.
I am going to attempt fix the problem by manually creating all config files, but wasn't sure if this is normal behavior so wanted to report..

following the setup, guide I created the docker instance and assigned the correct folders.
I checked to see that the host/volumes are created, and they are, but the .jf-accounts directory is completely empty.  The container fails to start, exit with code 1.

Traceback (most recent call last):

  File "/usr/local/bin/jf-accounts", line 4, in <module>

    __import__('pkg_resources').run_script('jellyfin-accounts==0.1', 'jf-accounts')

  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 667, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1464, in run_script

    exec(code, namespace, namespace)

  File "/usr/local/lib/python3.8/site-packages/jellyfin_accounts-0.1-py3.8.egg/EGG-INFO/scripts/jf-accounts", line 73, in <module>

    log = create_log('main')

  File "/usr/local/lib/python3.8/site-packages/jellyfin_accounts-0.1-py3.8.egg/EGG-INFO/scripts/jf-accounts", line 60, in create_log

    if config.getboolean('ui', 'debug'):

  File "/usr/local/lib/python3.8/configparser.py", line 828, in getboolean

    return self._get_conv(section, option, self._convert_to_boolean,

  File "/usr/local/lib/python3.8/configparser.py", line 808, in _get_conv

    return self._get(section, conv, option, raw=raw, vars=vars,

  File "/usr/local/lib/python3.8/configparser.py", line 803, in _get

    return conv(self.get(section, option, **kwargs))

  File "/usr/local/lib/python3.8/configparser.py", line 781, in get

    d = self._unify_values(section, vars)

  File "/usr/local/lib/python3.8/configparser.py", line 1149, in _unify_values

    raise NoSectionError(section) from None

configparser.NoSectionError: No section: 'ui'

**Comment by hrfee** [comment]
The docket container uses the directory `/jf` instead of `.jf-accounts`, so make sure you’ve mounted it there on the container. Does that fix it?

**Comment by DER31K** [comment]
> The docket container uses the directory `/jf` instead of `.jf-accounts`, so make sure you’ve mounted it there on the container. Does that fix it?

everything was mounted fine, the config file just wasn't created... I manually created it using the config_defualt.ini here

/jf was mounted to my host at /docker/jellyfin (this is my jellyfin directory)
/.jellyfin-accounts was mounted to my host at /docker/jellyfin-accounts
EDIT: /data was mounted to my host at /docker/jellyfin accounts

within the /docker/jellyfin-accounts/ folder , the config.ini wasn't created automatically by the docker instance. so I created it manually based on config-default.ini (https://github.com/hrfee/jellyfin-accounts/blob/master/data/config-default.ini), then restarted the container and it works....   is this normal install procedure to manually create the config file?

**Comment by hrfee** [comment]
Ah apologies, I meant `/data` instead of `.jf-accounts`, but if you say it works, I assume you’ve mounted it there anyway. Are you sure it’s not a permissions issue and it can’t create the file there?

**Comment by hrfee** [comment]
e.g `-v /path/to/.jf-accounts:/data`.

**Comment by DER31K** [comment]
I edited my post, yes /data was mounted to my host.
and yes I believe it is a permissions issue that caused files to not be created - closing issue.
