### ISSUE TITLE
feature request, invite system accessible to all jellyfin users.

### ISSUE THREAD

**Issue by DER31K** [hrfee/jellyfin-accounts#11]
This is a feature request, not a bug.

Would it be possible to link the authentication of the admin/invites page to the jellyfin user account profiles?  So that users can login with their credentials and invite others?

Alternatively, can the invite system currently be controlled programatically ie, through a web-api or cli?
My thought is that I could simply build a form on my own separate webpage where any user can just enter an email address to send an invite.

my use case: 
I'd like all users on my jellyfin server (close friends and family only) to be able to invite others, i trust my family/friends will use this with discretion.

**Comment by hrfee** [comment]
This is a really good idea, and should be quick to implement. I'll add it later tonight if i have the time. 

Also, yes there is a web API, which the web pages simply call through ajax requests in jquery. It's a little rough, but if you run jf-accounts, you can use the web api through the endpoints in `web_api.py` either using the username and password you set as auth, or first sending these to `/getToken` and using this token for auth alone.

**Comment by DER31K** [comment]
@hrfee thanks for all your help on this project!

FYI - and for any future google-rs
Thanks to your tip on the web API,  I ended up creating a page accessible to my users and via a jquery POST send the invite by email.

Personally, this is probably better for my system/flow than training/telling my users to login to the actual jf-accounts page with their credential.

Also i set hours to 730 (which is not possible on the web-ui) which makes invitation expiry 30 days, instead of 24 hours.... makes the expiry countdown show weird on the web-ui and on the email, but works!

![image](https://user-images.githubusercontent.com/8566394/80268606-9dcde200-8676-11ea-8589-dbcc8cdb333a.png)


> $.ajax({
>     url: 'https://JF-ACCOUNTS.URL:PORT/generateInvite',
>     type: 'post',
>     contentType:"application/json",
> 
> 
>     headers: {
>         Authorization: 'Basic BASE64-ENCODED-AUTH-HERE='
>     },
>     datatype : "json",
>     jsonp : "jsonp",
>     data: JSON.stringify({
>         email: $("#email").val(),  
>         hours: "730",
>         minutes: "0"
>     }),
>     success: function (data) {
>         console.info(data);
>     }
> });

**Comment by hrfee** [comment]
Sorry for taking so long on this, but b9cefcc11169e82beae47f4bd654b9f0febf6351 allows auth through jellyfin with the `jellyfin_login` and `admin_only` options.
