### ISSUE TITLE
Has to be installed on same host as Jellyfin?

### ISSUE THREAD

**Issue by tzw9373** [hrfee/jellyfin-accounts#14]
Your docker install directions mention mounting a volume from the path to the Jellyfin config directory, is this where your Jellyfin install lives? I run my Jellyfin natively on Windows and would like to run jellyfin-accounts on docker on an Ubuntu VM.

**Comment by hrfee** [comment]
Yes you can do this. Figure out where jellyfin puts your passwordreset*.json files by trying to reset your password, then add `-v <path to whatever folder jellyfin tells you it put the passwordreset.json in>:/jf` to your `docker create` command.
