### ISSUE TITLE
Google SMTP fails

### ISSUE THREAD

**Issue by DesertCookie** [hrfee/jellyfin-accounts#15]
Sending an email via Google's SMTP servers always fails. Is there more to it than pluggin in the correct data into JF-Accounts and enabling insecure apps for the Google account?

Thanks.

**Comment by hrfee** [comment]
I've tried this before but quit when I read that you had to disable 2FA or something. Could you run the program in debug mode (`debug = true` in the ui section of your config file) and send the log it outputs when you try to send an email? ofc censor anything personal.

**Comment by DesertCookie** [comment]
Where can I find the log? I'm running JF-Accounts in Docker.

**Comment by hrfee** [comment]
`docker logs -f <your container name>`

**Comment by DesertCookie** [comment]
Here's my log from shortly before the creation of a new invite:
```
xLLLhBOrFK8_jKEe5b4hsYbqYdM2nveUv7Oi4yI5g
 auth - DEBUG - HTTPAuth Allowed
 waitress - DEBUG - Creating new invite: 27R61p7M90exOWDDGday0g
 waitress - INFO - Sending invite to target.email@gmail.com
 emails - DEBUG - target.email@gmail.com: Creating email
 emails - DEBUG - target.email@gmail.com: Sending from rh.srv.de@gmail.com (Jellyfin)
 emails - DEBUG - target.email@gmail.com: Using subject Einladung - Jellyfin
 emails - DEBUG - target.email@gmail.com: Constructing email content
 emails - DEBUG - target.email@gmail.com: Using 24h time
 emails - DEBUG - target.email@gmail.com: Expires in 11h 59m
 emails - INFO - target.email@gmail.com: text constructed
 emails - INFO - target.email@gmail.com: html constructed
 auth - DEBUG - Verifying auth
 auth - DEBUG - verifying token eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDA5MjI3MiwiZXhwIjoxNTkwMDkzNDcyfQ.eyJpZCI6IjBhZjBkNmQ5YjY4MDQ0MmE5ZTYxOTRiM2Y1YTAwYTcwIn0.onKEA098g7ga_C-qPyZTEMPlNuX6V6TBUnpxiC1moH1DXxLLLhBOrFK8_jKEe5b4hsYbqYdM2nveUv7Oi4yI5g
 auth - DEBUG - HTTPAuth Allowed
 waitress - DEBUG - Invites requested
 emails - ERROR - target.email@gmail.com: Failed to send via smtp: ConnectionRefusedError
 waitress - INFO - New invite created: 27R61p7M90exOWDDGday0g
 auth - DEBUG - Verifying auth
 auth - DEBUG - verifying token eyJhbGciOiJIUzUxMiIsImlhdCI6MTU5MDA5MjI3MiwiZXhwIjoxNTkwMDkzNDcyfQ.eyJpZCI6IjBhZjBkNmQ5YjY4MDQ0MmE5ZTYxOTRiM2Y1YTAwYTcwIn0.onKEA098g7ga_C-qPyZTEMPlNuX6V6TBUnpxiC1moH1DXxLLLhBOrFK8_jKEe5b4hsYbqYdM2nveUv7Oi4yI5g
 auth - DEBUG - HTTPAuth Allowed
 waitress - DEBUG - Invites requested
```

**Comment by hrfee** [comment]
ConnectionRefusedError is what someone else received too when i was helping them. You don't have 2FA on your google account right? And what are your settings in the [smtp] section of your config? Make sure you're using port 465 is using ssl_tls, or 587 for starttls.

**Comment by DesertCookie** [comment]
I have enabled [Less secure apps](https://support.google.com/accounts/answer/6010255?hl=en) as pointed out by [this](https://www.digitalocean.com/community/tutorials/how-to-use-google-s-smtp-server) article. Here's an excerpt of my config:
```
method = smtp
address = my.jf.mail@gmail.com
```
```
encryption = ssl_tls
server = smtp.gmail.com
port = 465
password = google_pw
```

**Comment by hrfee** [comment]
And what about the `port` and `encryption` settings?

**Comment by DesertCookie** [comment]
*Edited previous comment.*

I just realised: Do I need to forward the port by any chance?

Edit: Doesn't seem to make a change, so I guess no port-forwarding is needed :P.

**Comment by hrfee** [comment]
Could you try this in a python console?
```
Python 3.8.2 (default, Apr  8 2020, 14:31:25) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl, smtplib
>>> context = ssl.create_default_context()
>>> with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as server:
...     server.ehlo()
...     server.login('your email address', 'your password')
... 
```
Fill in your username and password, and send back any errors that come up.

**Comment by DesertCookie** [comment]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 1034, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout,
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 253, in __init__
    (code, msg) = self.connect(host, port)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 339, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 1040, in _get_socket
    new_socket = socket.create_connection((host, port), timeout,
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Username\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] <German error description>
```

**Comment by hrfee** [comment]
10060 apparently means it couldn't connect to the address, so thats not super helpful. Could you check if IMAP is enabled in the gmail settings like this? ![settings](https://dump.hrfee.pw/20200521_22h05m41s_grim.png)

**Comment by hrfee** [comment]
Also, unrelated but are you using the latest version? I've just noticed the "send invite to address" thing on the admin page isn't working for me.

Edit: Just noticed a typo in the code, have no idea how it got in there. Don't update your docker container for now while i rebuild it.

**Comment by DesertCookie** [comment]
IMAP was disabled. I enabled it, which did not solve the problem.

Waiting for the update. I was using a version twelve days old.

**Comment by hrfee** [comment]
Alright. If you go [my account](https://myaccount.google.com/), then the Security tab, Is there an App Passwords option under 'Signing in to Google'? If there is, Go in there and create a new one with app type 'Email' and Device 'Other (Custom Name)', and call it whatever. Then it will give you a password. Try using that.

**Comment by hrfee** [comment]
Also the docker build is up now if you wanna update

**Comment by DesertCookie** [comment]
There is no app password option for me. Only my normal password, phone-sign-in, and 2FA.

Updating now.

Edit: Still a `ConnectionRefusedError`. | It seems like app passwords can only be set with 2FA enabled.

**Comment by DesertCookie** [comment]
Just found out Google dropped SSL support in 2016 and only supports TLS (found [here](https://community.spiceworks.com/topic/1682664-gmail-smtp-stopped-working)). That couldn't be the problem though since `ssl_tls` covers both protocols...?

**Comment by hrfee** [comment]
It works for me using the App Password, so maybe it's only enabled then? Anyway, if i run the same python code above but remove the last line (server.login) i get this
```
(250, b'smtp.gmail.com at your service, [your ip]\nSIZE 35882577\n8BITMIME\nAUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH\nENHANCEDSTATUSCODES\nPIPELINING\nCHUNKING\nSMTPUTF8')
```
The only way i could imagine this not working for you is if you had a firewall or something blocking the port?

**Comment by DesertCookie** [comment]
I enabled 2FA and created an app password. I have port 465 opened in my firewall.

Edit: I just realised all my traffic is going through a VPN (VPN server is a VPS that's running my reverse-proxy). Allowing Python to bypass the VPN I get an "at your service"-message. So far so good. How do I allow Docker to bypass the VPN though - more precisely the single container since my other containers rely on communicating with the VPS as their reverse proxy? I feel like this might be more than can be reasonably accomplished.

**Comment by hrfee** [comment]
[this](https://stackoverflow.com/questions/32052975/how-could-i-bind-docker-container-to-specific-external-interface) looks helpful. If you specify `-p <your local IP>:465:465` maybe it could get past the VPN?

**Comment by DesertCookie** [comment]
That looks very helpful, thank you. It looks like there are some [complications](https://stackoverflow.com/questions/39159740/docker-for-windows-cannot-assign-requested-address) because of me using Docker Desktop for Windows. That's something I will look into tomorrow.

**Comment by hrfee** [comment]
Ah ok, not sure i can help much more then. It seems like most people's issues are windows-related rn lol

**Comment by DesertCookie** [comment]
Windows is not ideal for this server stuff, yes. I'm locked into Windows because I'm running Windows software RAID (hardware controllers are dammn expensive!). Let's hope I get this working. If not, I'll send out the invites some other way (maybe a custom Docker container listening to changes in `invistes.json`).

**Comment by DesertCookie** [comment]
It seems like the problem is solved by not having a VPN running on the same machine. Even though Docker and therefore JF-Accounts traffic does not go through the VPN, it still seems to break SMTP.
