### ISSUE TITLE
Info about upcoming changes

### ISSUE THREAD

**Issue by Spiritreader** [hrfee/jellyfin-accounts#20]
In the upcoming Jellyfin 10.6, the default authentication providers will change from ```Emby.Server.Implementations.Library.DefaultAuthenticationProvider``` and
```Emby.Server.Implementations.Library.DefaultPasswordResetProvider``` 

to

```Jellyfin.Server.Implementations.Users.DefaultAuthenticationProvider``` and
```Jellyfin.Server.Implementations.Users.DefaultPasswordResetProvider```

This is because the old database setup for managing users has been unified and moved into one single EFCore database, which now stores, users, preferences and policies.

[Changes can be found here](https://github.com/jellyfin/jellyfin/tree/9af6eda0b495649e3a77694b2bb30abad1a26484/Jellyfin.Server.Implementations/Users)

All existing json user templates will have to be modified for 10.6.

So far it looks like nothing else breaks. User creation functions as expected on 10.6 so far after adjusting the AuthProvider.

**Comment by hrfee** [comment]
Thanks for informing me. You're right, the only changes needed are AuthenticationProviderId and PasswordResetProviderId.
