### ISSUE TITLE
Optionally set e-mail as username

### ISSUE THREAD

**Issue by YKPDang** [hrfee/jellyfin-accounts#22]
It would be nice to have the option to set the e-mail as the username automatically. That way it would be easier for admins to contact the users instead of having to figure out first who is behind a username.

**Comment by hrfee** [comment]
Added in 68a459023cb6c62055d3b5c302c221e3bc53e39c

in the config, set 'no_username' in the 'email' section to true to disable username input and use the email address instead. I'll add the option to the web UI eventually too.
