### ISSUE TITLE
No donation link

### ISSUE THREAD

**Issue by YKPDang** [hrfee/jellyfin-accounts#23]
I've looked a little bit around and have found no donation link. Could you please add a donation link, such that we can support you a little bit?

**Comment by Spiritreader** [comment]
Can confirm. Could not find donation link (preferrably paypal).

**Comment by hrfee** [comment]
I really think people's money is better to be given to other projects like Jellyfin itself, but i'll add a paypal.me link to the readme.

**Comment by hrfee** [comment]
See 00ba11940ab4c372c142065398165894eb3cb315
