### ISSUE TITLE
How can I install that on Raspberry Pi ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [hrfee/jellyfin-accounts#27]
Hi,

I'm trying to install that on my raspberry pi, but I can't manage to do it. Here is the error I have:
![image](https://user-images.githubusercontent.com/64923542/86510848-d8c96000-bdf3-11ea-948a-08caeece74c7.png)

I searched about the issue, didn't find anything useful. Could someone help me please ?
Thanks in advance.
Have a good day

**Comment by hrfee** [comment]
You’re using pip from python 2.7, when you need it from python 3.x. Try `pip3 install jellyfin-accounts` instead.

**Comment by LeVraiRoiDHyrule** [comment]
Thanks, it worked. Everything is now installed. 

But I can't access http://[myip]:8056/ , I don't know why:
![image](https://user-images.githubusercontent.com/64923542/86511196-fcda7080-bdf6-11ea-8215-f8b1091b289a.png)

I checked my router, there is nothing blocking the port 8056. What should I check to find the issue ?

**Comment by hrfee** [comment]
Could you send the full output of `jf-accounts`?

**Comment by LeVraiRoiDHyrule** [comment]
How do I do that?

**Comment by hrfee** [comment]
You need to actually run `jf-accounts` to start the server. For me, this looks like
```
λ jf-accounts                                                                                                                                (~) 13:51:53
 main - DEBUG - Using default invites
 main - DEBUG - Using default emails
 main - DEBUG - Using default user_template
 main - DEBUG - Using default user_configuration
 main - DEBUG - Using default user_displayprefs
 main - DEBUG - Using default password reset email HTML template
 main - DEBUG - Using default password reset email plaintext template
 main - DEBUG - Using default invite email HTML template
 main - DEBUG - Using default invite email plaintext template
 auth - DEBUG - Using jellyfin for admin authentication
 waitress - INFO - Successfully authenticated with http://192.168.1.252:8096
 main - INFO - Starting web UI on 0.0.0.0:8056
 main - INFO - Starting email thread
 emails - INFO - Monitoring /tmp/testdir
 emails - ERROR - Directory /tmp/testdir does not exist
Serving on http://0.0.0.0:8056
``` 
Once it's running, just copy the terminal output and paste it here inside between two \`\`\`, e.g:
\`\`\`
log goes here
\`\`\`

**Comment by LeVraiRoiDHyrule** [comment]
I just forgot to start the server, I'm an idiot. Sorry for bothering you. I've got the config page, it should go without issues.
thanks a lot for your help and sorry again.

**Comment by hrfee** [comment]
no problem, i'll keep this open for a bit incase you run into any other issues.

**Comment by LeVraiRoiDHyrule** [comment]
It works great, I have no issue for now. I just have a question : Is it possible to set a link for jellyfin-account on the jellyfin login page ?

**Comment by hrfee** [comment]
Definitely possible, not sure how though. You could probably edit the login page if you could find the file, or [JFTool](https://github.com/BobHasNoSoul/JFTool) might have some option to do this.
