### ISSUE TITLE
Not sure where I went wrong..

### ISSUE THREAD

**Issue by coolcat97** [hrfee/jellyfin-accounts#31]
Cannot generate invite codes, is something missing? Running on docker. No errors. 

[Here's my page view.](https://ibb.co/nR4Yh0j)

**Comment by hrfee** [comment]
Could you go into the console, refresh and look for errors? (Right Click > Inspect Element > Console)

**Comment by hrfee** [comment]
Nevermind, I've got the same problem when I do a clean install, I really gotta up my testing game.

**Comment by hrfee** [comment]
I'm assuming you didn't enable invite emails? I'll fix this now.

**Comment by coolcat97** [comment]
I can help you test! :) lol - but yes, no invite emails.. I was just going to put an invite link on my discord

**Comment by hrfee** [comment]
Fixed in 7bda2f4141349b694497540ea6a2545c4924899d
Update and try now.

**Comment by coolcat97** [comment]
Fixed! :) Awesome, thanks!
