### ISSUE TITLE
Feature request: No expire invites

### ISSUE THREAD

**Issue by coolcat97** [hrfee/jellyfin-accounts#32]
Hello! Was wondering if it's possible to let invites never expire?

**Comment by hrfee** [comment]
Yeah ok, I'll add this tonight or tomorrow, currently refactoring admin page js so i'll add it when i've done that. Also, just to clarify, you mean an invite with no time limit right? Not an invite that never becomes invalid (e.g can be used multiple times)

**Comment by coolcat97** [comment]
Both would be awesome!!!

 


Like no time limit to accept and can be used multiple times

**Comment by hrfee** [comment]
I'll add multi-use invites, and also let you specify how many times it can be used. I'll add a warning though, as it's a bit dangerous if the link gets shared around. Maybe i'll add a little info menu that tells you how many times a code has been used, too.

**Comment by coolcat97** [comment]
> I'll add multi-use invites, and also let you specify how many times it can be used. I'll add a warning though, as it's a bit dangerous if the link gets shared around. Maybe i'll add a little info menu that tells you how many times a code has been used, too.

That would be awesome!!

**Comment by hrfee** [comment]
Added in 27169e4e0d0f4a3707ca0c6a8538b44840adf2d4
Try it out and see if there's anything i missed.
