### ISSUE TITLE
How to start the configuration page again ?

### ISSUE THREAD

**Issue by cryptdrive** [hrfee/jellyfin-accounts#35]
Hey I entered stuff in the configuration for testing purpose now I want to change my smtp details and other things . Is there any way to get the configuration page again ?

Also I want to restrict users from transcoding , is there anyway I can disable this automatically when a user is created ?

**Comment by hrfee** [comment]
You can change settings in the settings menu in the top left of the admin page. If you really wanted to, you could delete the ~/.jf-accounts folder to restart initial setup but that would also remove emails and templates. For your second request, I expect that setting will be stored in one of the templates, but let me check for you.

**Comment by hrfee** [comment]
Yeah, all of the "allow transcoding" settings are stored in the user template. Also just noticed that the "new user defaults" feature isn't working for me right now. Give me a minute to fix it, and after that you'll be able to set defaults.

**Comment by hrfee** [comment]
Ok, fixed in f2966ef81032d4e54293041b9b6071c2c3d91ce0
Create a temporary user with your preferred settings, then in jf-accounts, go to settings > new user defaults, and select the user to store the settings.
