### ISSUE TITLE
How do I run this program on Raspberry Pi ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [hrfee/jellyfin-accounts#37]
Hi,
I'm a begginer in raspberry, python and nearly everything.

I successfully installed jellyfin-accounts with pip3 install jellyfin-accounts on my pi.
But I didn't find how to just run the program. It is not written in the wiki.
How do I do ? Could someone help me ?

Thanks in advance for your help and have a good day.

**Comment by hrfee** [comment]
Didn't you already ask this in #27? Also try jfa-go as I'm not updating this anymore.

**Comment by LeVraiRoiDHyrule** [comment]
Yeah, I asked this but I forgot how I did last time. Sorry for asking again.
I'll try jfa-go but I guess I would have the same question for jfa-go.

**Comment by hrfee** [comment]
I'll get back to you with a quick explanation later.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> I'll get back to you with a quick explanation later.

Just managed how to do with JF-go, it's way easier. Sorry for disturbing and have a good day
