### ISSUE TITLE
managed to start service - but stuck on page#3

### ISSUE THREAD

**Issue by mairajha** [hrfee/jellyfin-accounts#40]
managed to start service - but stuck on page#3 where I have to enter user details, create one admin user from jellyfin and fill it's credentials on jf-accounts but when I press test it says failed. . .

_Originally posted by @mairajha in https://github.com/hrfee/jellyfin-accounts/issues/36#issuecomment-726099225_

**Comment by hrfee** [comment]
I don't maintain this anymore. Can you try with jfa-go instead?
