### ISSUE TITLE
Unable to send email via smtp

### ISSUE THREAD

**Issue by mairajha** [hrfee/jellyfin-accounts#41]
able to start the service and after configuration got below mentioned errors. Kindly take a look

 waitress - INFO - Config modification requested
 waitress - INFO - Config written.
 waitress - INFO - Sending invite to syedmairaj@hotmail.com
 emails - INFO - syedmairaj@hotmail.com: text constructed
 emails - INFO - syedmairaj@hotmail.com: html constructed
 emails - ERROR - syedmairaj@hotmail.com: Failed to send via smtp (SMTPServerDisconnected: ('Connection unexpectedly closed',))
 waitress - INFO - New invite created: EIUwXan-1qoTWx2vJ-9jWQ
 waitress - INFO - Config modification requested
 waitress - INFO - Config written.
 waitress - INFO - Sending invite to syedmairaj@hotmail.com
 emails - INFO - syedmairaj@hotmail.com: text constructed
 emails - INFO - syedmairaj@hotmail.com: html constructed
 emails - ERROR - syedmairaj@hotmail.com: Failed to send via smtp (SSLError: (1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)'))
 waitress - INFO - New invite created: fNr9wFNZfPtmdfbQygtBfA
 waitress - INFO - Config modification requested
 waitress - INFO - Config written.
 waitress - INFO - Sending invite to syedmairaj@hotmail.com
 emails - INFO - syedmairaj@hotmail.com: text constructed
 emails - INFO - syedmairaj@hotmail.com: html constructed
 emails - ERROR - syedmairaj@hotmail.com: Failed to send via smtp (SMTPServerDisconnected: ('Connection unexpectedly closed',))
 waitress - INFO - New invite created: GPzLwCni0Lx4X2vgE8kj4g

**Comment by hrfee** [comment]
i'm not gonna offer any support for this, switch to jfa-go.

**Comment by hrfee** [comment]
it looks like you've just used the wrong port number or encryption type btw
