### ISSUE TITLE
Cannot creat user in jellyfin

### ISSUE THREAD

**Issue by gadgetusaf** [hrfee/jellyfin-accounts#43]
I am running the unstable version in docker and cannot get it to create a new user in jellyfish. I can create the invite but when we try to test it fails to create the user and stays on the account creation pange. 

`
form.js:1 GET https://MY.Domainm/invite/0xbd64e0/lang/form 404
g @ form.js:1
v @ form.js:1
(anonymous) @ form.js:1
(anonymous) @ form.js:1
site.webmanifest:1 GET https://MY.Domain/invite/0xbd64e0/site.webmanifest 404
site.webmanifest:1 Manifest: Line: 1, column: 1, Syntax error.
rFXZQhzRQQSC7pLBSKHZY5:1 The resource https://MY.Domain/css/remixicon.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
rFXZQhzRQQSC7pLBSKHZY5:1 The resource https://MY.Domain/css/bundle.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
form.js:1 POST https://MY.Domain/invite/0xbd64e0/newUser 404
f @ form.js:1
M @ form.js:1
`

**Comment by hrfee** [comment]
wrong repo, put this on jfa-go if you're still having problems.
