### ISSUE TITLE
[Feature Request] Password Requirements

### ISSUE THREAD

**Issue by linetrimmer** [hrfee/jellyfin-accounts#7]
I think it would be helpful if you could choose to require that passwords meet certain criteria before the account can be created

**Comment by hrfee** [comment]
Added this feature in 690de58e9ffdb3f267eab5029022989eb27151b9
Supports minimum length, number of uppercase and special characters, and numbers. Are there any obvious ones I've missed out?

**Comment by linetrimmer** [comment]
Thanks for the quick addition. Maybe lowercase characters, too?

I'm running into an issue now where if special = 0, the password requirements box does not change uppercase letters from red to green even if there is an uppercase letter in the password. It'll still make the account if the requirements actually are met, but it doesn't pop up with a successful account creation message after.

**Comment by hrfee** [comment]
I see the issue on mine too now, sorry for closing this so early. I'll work on this now

**Comment by hrfee** [comment]
Sorry this was a dumb one. If you set one of the criteria to 0, the javascript on the site just doesn't add it to the page. Then when the backend validates a password, the page tries to loop through each criteria and find it's element on the page, and ofc one of them doesn't exist, so it errors out and refuses to do the rest.

I just fixed this and added the lowercase option in 4df78a22c5a2a48cc72d936c4002528ba8ea7d6b
