### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by MiTvSpain** [hrfee/jellyfin-accounts#8]
Best match: python-ldap 3.2.0
Processing python-ldap-3.2.0.tar.gz
Writing /tmp/easy_install-96wkbplz/python-ldap-3.2.0/setup.cfg
Running python-ldap-3.2.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-96wkbplz/python-ldap-3.2.0/egg-dist-tmp-bhy9_8zk
no previously-included directories found matching 'Doc/.build'

In file included from Modules/LDAPObject.c:3:0:
Modules/common.h:9:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.

**Comment by hrfee** [comment]
Are you on Debian or Ubuntu? If so, try
`sudo apt install python-dev python3-dev`.

**Comment by MiTvSpain** [comment]
ubuntu

I already did that process before running the installation application and it gave me the error.

**Comment by hrfee** [comment]
Try running that command then.

**Comment by MiTvSpain** [comment]
correct installation now, now I am going to see how to configure it

**Comment by hrfee** [comment]
Great. I’ll add this to the install guide for others
